# Generated by Django 6.0.4 on 2026-04-23 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_budgethistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='budgethistory',
            name='titre',
            field=models.CharField(default='', max_length=255),
        ),
    ]
