# Generated by Django 6.0.4 on 2026-04-23 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_budgethistory_titre'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Depense',
        ),
    ]
