# Generated by Django 6.0.4 on 2026-04-23 08:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_depense'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='depense',
            name='montant',
        ),
        migrations.AlterField(
            model_name='depense',
            name='montant_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='depense',
            name='titre',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.CreateModel(
            name='DepenseItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('prix', models.DecimalField(decimal_places=2, max_digits=10)),
                ('depense', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='api.depense')),
            ],
        ),
    ]
