# Generated by Django 6.0.4 on 2026-04-23 13:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_depense_montant_alter_depense_montant_total_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='depense',
            name='added_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='added_depenses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='depense',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='APPROVED', max_length=20),
        ),
        migrations.AlterField(
            model_name='depense',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='depenses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='UserAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_level', models.CharField(choices=[('FULL', 'Full Access'), ('LIMITED', 'Limited Access')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shared_accesses_given', to=settings.AUTH_USER_MODEL)),
                ('shared_with', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shared_accesses_received', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('owner', 'shared_with')},
            },
        ),
    ]
