# Generated by Django 6.0.4 on 2026-04-24 11:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_depense_added_by_depense_status_alter_depense_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='access_level',
            field=models.CharField(blank=True, choices=[('FULL', 'Full'), ('LIMITED', 'Limited')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='associates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ASSOCIER', 'ASSOCIER'), ('MANAGER', 'MANAGER'), ('ADMIN', 'ADMIN')], default='MANAGER', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='temp_manager_email',
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
    ]
